Repository pypa/flit, pull requests merged in 2021-11, with the labels that each got.

#463 Update README.rst for flit_core >=3.2 metadata
  README.rst
  doc/pyproject_toml.rst
Labels: documentation

#464 Require newer Sphinx for building docs on RTD
  doc/requirements.txt
Labels: documentation

#468 Namespace package support
  .gitignore
  flit/install.py
  flit/sdist.py
  flit_core/flit_core/common.py
  flit_core/flit_core/config.py
  flit_core/flit_core/tests/samples/ns1-pkg/EG_README.rst
  flit_core/flit_core/tests/samples/ns1-pkg/ns1/pkg/__init__.py
  flit_core/flit_core/tests/samples/ns1-pkg/pyproject.toml
  flit_core/flit_core/tests/test_common.py
  flit_core/flit_core/tests/test_config.py
  tests/samples/ns1-pkg-mod/ns1/module.py
  tests/samples/ns1-pkg-mod/pyproject.toml
  tests/samples/ns1-pkg/EG_README.rst
  tests/samples/ns1-pkg/ns1/pkg/__init__.py
  tests/samples/ns1-pkg/pyproject.toml
  tests/samples/ns1-pkg2/EG_README.rst
  tests/samples/ns1-pkg2/ns1/pkg2/__init__.py
  tests/samples/ns1-pkg2/pyproject.toml
  tests/test_build.py
  tests/test_install.py
  tests/test_sdist.py
  tests/test_wheel.py
Labels: enhancement

#470 Fix docs to say that --no-setup-py is the default
  doc/cmdline.rst
Labels: documentation

#472 Fix development installs
  flit/install.py
  flit_core/flit_core/common.py
  tests/test_install.py
Labels: bug
