Repository pypa/flit, pull requests merged in 2022-08, with the labels that each got.

#576 Update link to external pip environment variables docs
  doc/cmdline.rst
Labels: documentation

#571 Support optional installation root
  flit_core/bootstrap_install.py
Labels: enhancement

#567 Catch errors getting/setting password with keyring
  flit/upload.py
  tests/test_upload.py
Labels: bug

#566 Normalize module name default value
  doc/pyproject_toml.rst
  flit_core/flit_core/config.py
  flit_core/flit_core/tests/samples/normalization/my_python_module.py
  flit_core/flit_core/tests/samples/normalization/pyproject.toml
  flit_core/flit_core/tests/test_config.py
Labels: enhancement
