Repository pypa/flit, pull requests merged in 2022-02, with the labels that each got.

#510 External data directory
  doc/pyproject_toml.rst
  flit/install.py
  flit_core/flit_core/common.py
  flit_core/flit_core/config.py
  flit_core/flit_core/sdist.py
  flit_core/flit_core/tests/samples/with_data_dir/LICENSE
  flit_core/flit_core/tests/samples/with_data_dir/README.rst
  flit_core/flit_core/tests/samples/with_data_dir/data/share/man/man1/foo.1
  flit_core/flit_core/tests/samples/with_data_dir/module1.py
  flit_core/flit_core/tests/samples/with_data_dir/pyproject.toml
  flit_core/flit_core/tests/test_sdist.py
  flit_core/flit_core/tests/test_wheel.py
  flit_core/flit_core/wheel.py
  tests/test_install.py
Labels: enhancement

#511 Add bootstrap script/wheel module for flit_core
  doc/bootstrap.rst
  flit_core/bootstrap_install.py
  flit_core/flit_core/tests/test_wheel.py
  flit_core/flit_core/wheel.py
  flit_core/pyproject.toml
Labels: enhancement

#528 Release notes for 3.7
  doc/history.rst
  doc/pyproject_toml.rst
Labels: documentation

#531 Fix relative imports in __init__.py when exec-ing to get __version__
  doc/history.rst
  flit_core/flit_core/common.py
  flit_core/flit_core/tests/samples/imported_version/package1/__init__.py
  flit_core/flit_core/tests/samples/imported_version/package1/_version.py
  flit_core/flit_core/tests/samples/imported_version/pyproject.toml
  flit_core/flit_core/tests/test_common.py
Labels: bug
