Repository pypa/flit, pull requests merged in 2025-03, with the labels that each got.

#725 Add additional check for project.license.file
  flit_core/flit_core/config.py
  flit_core/tests_core/test_config.py
Labels: bug

#731 Support compound SPDX licence expressions
  flit_core/flit_core/config.py
  flit_core/tests_core/test_common.py
  flit_core/tests_core/test_config.py
Labels: enhancement

#737 Prepare to release 3.12
  .bumpversion.cfg
  doc/conf.py
  doc/history.rst
  flit/__init__.py
  flit_core/flit_core/__init__.py
  pyproject.toml
Labels: documentation

#739 Update the bootstrap guide for ``tomllib``
  doc/bootstrap.rst
Labels: documentation
